### ISSUE TITLE
flutterwave not redirecting after successful payments even after specifying a redirect_url

### ISSUE THREAD

**Issue by godfreymutebi** [Flutterwave/Node-v3#121]
payload = {
        'tx_ref' => tx_ref,
        'amount' => amount,
        'email' => 'xxxxxxxx@gmail.com',
        'phone_number' => phone_number,
        'currency' => currency,
        'redirect_url' => 'http://localhost:3000/flutterwave',
        'network' => 'MTN'

      }

**Comment by Dekunledev** [comment]
Hi @godfreymutebi 
The provided payload includes a redirect_url parameter set to `'http://localhost:3000/flutterwave'.` This URL indicates a local development server endpoint, which is why Flutterwave is unable to redirect the user. To enable successful redirection, it's recommended to use a publicly accessible URL instead of a local development server URL
